version: '3'
services:
    mongo:
        image: mongo:3.0
    mongo_admin:
        image: mongo-express:latest
        links:
            - mongo
        ports:
            - 8081:8081
    node:
        image: node:9
        working_dir: /home/node/app
        environment:
            - PORT=${NODE_PORT}
            - AUTH0_DOMAIN=${AUTH0_DOMAIN}
            - AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
            - AUTH0_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
        links:
            - mongo
        ports:
            - 3000:3000
        volumes:
            - ./:/home/node/app
        command: 'yarn start'
